### ISSUE TITLE
belum daftar PSE

### ISSUE THREAD

**Issue by klawcodes** [rayasabari/caringab#1]
daftarin dulu ngab, takutnya diblokir kominfo xixix

**Comment by rayasabari** [comment]
> daftarin dulu ngab, takutnya diblokir kominfo xixix

wkwkwkw kan justru ini requestan mereka ngab

**Comment by klawcodes** [comment]
sekalian bikinin steam versi indo ngab, tapi isi gamenya Tahu Bulat sama Candy Crush Saga mod apk
